"use client";

import { useState } from "react";
import { Download, FileCode, ChevronRight, Package } from "lucide-react";
import JSZip from "jszip";
import { GeneratedFile } from "@/lib/parse-generated-files";

interface Props {
  files: GeneratedFile[];
}

const LANG_COLORS: Record<string, string> = {
  tsx: "text-blue-400",
  ts: "text-blue-400",
  typescript: "text-blue-400",
  jsx: "text-yellow-400",
  js: "text-yellow-400",
  javascript: "text-yellow-400",
  css: "text-pink-400",
  scss: "text-pink-400",
  html: "text-orange-400",
  json: "text-green-400",
  md: "text-gray-400",
  yaml: "text-purple-400",
  yml: "text-purple-400",
  py: "text-green-400",
  python: "text-green-400",
  sh: "text-gray-300",
  bash: "text-gray-300",
};

function FileIcon({ lang }: { lang: string }) {
  const color = LANG_COLORS[lang] || "text-gray-400";
  return <FileCode size={11} className={`shrink-0 ${color}`} />;
}

/** Build a simple folder-aware tree */
function buildFolderTree(files: GeneratedFile[]) {
  const folders: Record<string, GeneratedFile[]> = {};
  const root: GeneratedFile[] = [];

  for (const f of files) {
    const parts = f.path.split("/");
    if (parts.length === 1) {
      root.push(f);
    } else {
      const folder = parts.slice(0, -1).join("/");
      if (!folders[folder]) folders[folder] = [];
      folders[folder].push(f);
    }
  }
  return { root, folders };
}

function makeReadme(files: GeneratedFile[]): string {
  const hasPkg = files.find((f) => f.path === "package.json");
  const hasTs = files.some((f) => f.language === "typescript" || f.language === "tsx");
  return `# Generated App

Auto-generated by Eburon Codepilot.

## Files (${files.length})
${files.map((f) => `- \`${f.path}\``).join("\n")}

## Getting Started
${
  hasPkg
    ? `\`\`\`bash
npm install
${hasTs ? "npm run build\n" : ""}npm start
\`\`\``
    : "Open the files in your editor and follow the code comments."
}

> Generated with ❤️ by Eburon Model (maximus-cli)
`;
}

export default function GeneratedAppPreview({ files }: Props) {
  const [activeFile, setActiveFile] = useState<string>(files[0]?.path || "");
  const [downloading, setDownloading] = useState(false);
  const [openFolders, setOpenFolders] = useState<Set<string>>(
    () => new Set(files.map((f) => f.path.split("/").slice(0, -1).join("/")))
  );

  const current = files.find((f) => f.path === activeFile);
  const { root, folders } = buildFolderTree(files);

  async function downloadZip() {
    setDownloading(true);
    try {
      const zip = new JSZip();
      files.forEach((f) => zip.file(f.path, f.content));
      if (!files.find((f) => f.path === "README.md")) {
        zip.file("README.md", makeReadme(files));
      }
      const blob = await zip.generateAsync({ type: "blob" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = "generated-app.zip";
      a.click();
      URL.revokeObjectURL(url);
    } finally {
      setDownloading(false);
    }
  }

  function toggleFolder(folder: string) {
    setOpenFolders((prev) => {
      const next = new Set(prev);
      next.has(folder) ? next.delete(folder) : next.add(folder);
      return next;
    });
  }

  return (
    <div className="mt-3 rounded-xl border border-eburon-500/40 bg-gray-900/80 overflow-hidden shadow-xl shadow-black/30">
      {/* Header bar */}
      <div className="flex items-center justify-between px-4 py-2.5 bg-gradient-to-r from-eburon-900/60 to-purple-900/40 border-b border-eburon-500/20">
        <div className="flex items-center gap-2">
          <Package size={14} className="text-eburon-400" />
          <span className="text-sm font-semibold text-eburon-300">
            Generated App
          </span>
          <span className="text-xs text-gray-500 bg-gray-800 px-2 py-0.5 rounded-full">
            {files.length} files
          </span>
        </div>
        <button
          onClick={downloadZip}
          disabled={downloading}
          className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-eburon-600 hover:bg-eburon-500 active:scale-95 text-white text-xs font-medium transition-all disabled:opacity-50 shadow-md shadow-eburon-900/50"
        >
          <Download size={12} />
          {downloading ? "Packaging…" : "Download ZIP"}
        </button>
      </div>

      <div className="flex" style={{ height: "320px" }}>
        {/* File tree */}
        <div className="w-52 shrink-0 border-r border-gray-700/60 overflow-y-auto bg-gray-950/40 py-1.5">
          {/* Root files */}
          {root.map((f) => (
            <FileRow
              key={f.path}
              file={f}
              active={activeFile === f.path}
              indent={0}
              onClick={() => setActiveFile(f.path)}
            />
          ))}
          {/* Folders */}
          {Object.entries(folders)
            .sort(([a], [b]) => a.localeCompare(b))
            .map(([folder, fFiles]) => (
              <div key={folder}>
                <button
                  onClick={() => toggleFolder(folder)}
                  className="w-full flex items-center gap-1 px-3 py-1 text-xs text-gray-400 hover:text-gray-200 hover:bg-gray-800/50 transition-colors"
                >
                  <ChevronRight
                    size={10}
                    className={`transition-transform shrink-0 ${openFolders.has(folder) ? "rotate-90" : ""}`}
                  />
                  <span className="truncate font-medium">
                    {folder.split("/").pop()}/
                  </span>
                </button>
                {openFolders.has(folder) &&
                  fFiles.map((f) => (
                    <FileRow
                      key={f.path}
                      file={f}
                      active={activeFile === f.path}
                      indent={1}
                      onClick={() => setActiveFile(f.path)}
                    />
                  ))}
              </div>
            ))}
        </div>

        {/* Code viewer */}
        <div className="flex-1 overflow-auto bg-gray-950/60">
          {current ? (
            <>
              {/* Tab bar */}
              <div className="flex items-center gap-2 px-4 py-1.5 border-b border-gray-700/50 bg-gray-900/60 sticky top-0">
                <FileIcon lang={current.language} />
                <span className="text-xs text-gray-300 font-mono">
                  {current.path}
                </span>
              </div>
              <pre className="text-xs text-gray-200 p-4 font-mono leading-relaxed whitespace-pre overflow-x-auto">
                <code>{current.content}</code>
              </pre>
            </>
          ) : (
            <div className="flex items-center justify-center h-full text-gray-600 text-sm">
              Select a file
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

function FileRow({
  file,
  active,
  indent,
  onClick,
}: {
  file: GeneratedFile;
  active: boolean;
  indent: number;
  onClick: () => void;
}) {
  const name = file.path.split("/").pop() || file.path;
  return (
    <button
      onClick={onClick}
      className={`w-full flex items-center gap-1.5 py-1 text-xs text-left truncate transition-colors ${
        active
          ? "bg-eburon-700/40 text-white"
          : "text-gray-400 hover:bg-gray-800/50 hover:text-gray-200"
      }`}
      style={{ paddingLeft: `${(indent + 1) * 12 + 4}px` }}
      title={file.path}
    >
      <FileIcon lang={file.language} />
      <span className="truncate">{name}</span>
    </button>
  );
}
